<?php

namespace PresenterLink;
?>
<style>#tracy-debug #presenter-link-panel a code {background-color: inherit; display: inline}</style>
<h1>Presenter <a href="<?php echo $editorLink($presenterClass); ?>"><?php echo $presenterClass->name; ?></a></h1>
<div id="presenter-link-panel">

    <p>
        Current action: <code><?php echo $actionName; ?></code>
        <br>
        Presenter file: <a href="<?php echo $editorLink($presenterClass); ?>" class="presenterlink-code"><code><?php echo substr($presenterClass->fileName, $appDirPathLength) ?></code></a>
        <br>
        Template file: <a
                href="<?php echo $editorLink($templateFileName); ?>"><code><?php echo substr($templateFileName, $appDirPathLength); ?></code></a>
        <br>
        Layout file: <a
                href="<?php echo $editorLink($layoutFileName); ?>"><code><?php echo substr($layoutFileName, $appDirPathLength); ?></code></a>
    </p>

    <p>
        <?php foreach ($interestedMethods as $method) { ?>
            Method
            <a href="<?php echo $editorLink($method); ?>"><code><?php echo $method->name ?></code></a>
            <?php echo "[{$method->startLine}-{$method->endLine}]"; ?>
            <br>
        <?php } ?>
    </p>

    <p>

    <div style="font-weight: bold;">Parent classes:</div>
    <ul style="margin-left: 25px;">
		<?php foreach ($parentClasses as $class) { ?>
        <li>
            <a href="<?php echo $editorLink($class["reflection"]); ?>"><code><?php echo $class["reflection"]->name; ?></code></a>
            <?php if (count($class["methods"]) > 0) { ?>
                <span style="font-size: 80%;">(
                    <?php foreach ($class["methods"] as $method) { ?>
                        <a href="<?php echo $editorLink($method); ?>"><?php echo $method->name; ?></a>
                    <?php } ?>
                    )</span>
			<?php } ?>
        </li>
		<?php } ?>
    </ul>
    </p>

    <p>

    <div style="font-weight: bold;">Attached components:</div>
    <ul style="margin-left: 25px;">
		<?php foreach ($usedComponentMethods as $method): ?>
        <li>
            <a href="<?php echo $editorLink($method['method']); ?>"><code><?php echo substr($method['method']->name, 15); ?></code></a>
        </li>
		<?php endforeach; ?>
    </ul>
    </p>

    <p>

    <div style="font-weight: bold;">Unused components:</div>
	<ul style="margin-left: 25px;">
		<?php foreach ($unusedComponentMethods as $method): ?>
			<li>
				<a href="<?php echo $editorLink($method['method']); ?>"><code><?php echo substr($method['method']->name, 15); ?></code></a>
			</li>
		<?php endforeach; ?>
	</ul>
    </p>
</div>
